"""Domain models for TRACE investigation components."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid

from pydantic import BaseModel, Field


class HypothesisStatus(str, Enum):
    """Lifecycle status of a debugging hypothesis."""
    PROPOSED = "PROPOSED"
    SUPPORTED = "SUPPORTED"
    WEAKENED = "WEAKENED"
    REJECTED = "REJECTED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    VERIFIED = "VERIFIED"
    DISPROVEN = "DISPROVEN"
    CONFIRMED = "CONFIRMED"  # Retained for v0.1.1 backwards compatibility


class StepStatus(str, Enum):
    """Execution status of a plan step."""
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


class Observation(BaseModel):
    """Deterministic or observational output generated by executing a tool."""
    id: str = Field(default_factory=lambda: f"obs_{uuid.uuid4().hex[:8]}")
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    tool_name: str
    input_args: Dict[str, Any] = Field(default_factory=dict)
    output_data: Dict[str, Any] = Field(default_factory=dict)
    is_success: bool = True
    summary: str
    evidence_tags: List[str] = Field(default_factory=list)
    error_message: Optional[str] = None


class Hypothesis(BaseModel):
    """A competing explanation for the observed bug."""
    id: str = Field(default_factory=lambda: f"hyp_{uuid.uuid4().hex[:6]}")
    statement: str
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    status: HypothesisStatus = HypothesisStatus.PROPOSED
    supporting_observation_ids: List[str] = Field(default_factory=list)
    contradictory_observation_ids: List[str] = Field(default_factory=list)
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    contradictory_evidence_ids: List[str] = Field(default_factory=list)
    counterexample_ids: List[str] = Field(default_factory=list)
    falsification_condition: str = ""
    rationale: str = ""


class PlanStep(BaseModel):
    """A single actionable step in the investigation plan."""
    step_id: int
    title: str
    tool_name: str
    tool_args: Dict[str, Any] = Field(default_factory=dict)
    expected_outcome: str
    status: StepStatus = StepStatus.PENDING
    observation_id: Optional[str] = None


class InvestigationPlan(BaseModel):
    """The current structured investigation plan."""
    objective: str
    steps: List[PlanStep] = Field(default_factory=list)
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    revision_count: int = 0


class FinalDiagnosis(BaseModel):
    """The final evidence-backed diagnosis delivered to the student."""
    problem_statement: str
    investigation_summary: str
    likely_root_cause: str
    evidence_summary: List[str] = Field(default_factory=list)
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)
    what_trace_checked: List[str] = Field(default_factory=list)
    what_remains_uncertain: List[str] = Field(default_factory=list)
    learning_point: str
    suggested_fix_guidance: str
    verified_hypothesis_id: Optional[str] = None
    countercheck_summary: Optional[str] = None
